/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-20-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class LearnGit {

    public static Integer myNumber = 20;
    
    public static String rebase = 'remote-origin';
    
    public static Integer rebase;

    public static string myName = 'GIT';

    public static void method() {
        System.debug('Updated in the main branch of Origin');
    }

    public static void method2() {
        System.debug('Sync the GIT from origin to local');
    }
}