/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-20-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class LearnGit {
    
    public static void method1() {
        System.debug('Learning the UI on GIT');
    }

    public static void method2() {
        System.debug('Sync the GIT from origin to local');
    }

    public static void method3() {
        System.debug(' origin to local changes');
    }

    public static void method4() {
        System.debug('new feature in local');
    }
}

