/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 11-19-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class MyFirstClass {

    public static integer myAge;

    public static void method2() {
    System.debug('This isdirectly comming from remote');
    }

    public static void method1() {
        System.debug('This is my local created');
    }
}


